### ISSUE TITLE
Error fetching xorg-xserver during parsing

### ISSUE THREAD

**Issue by haelyons** [JeffyCN/meta-rockchip#74]
Error when running the `bitbake show-layers` command before a first build for the recently added `rockchip-rk3568-rock3a` SBC.

The release mentioned in the `xserver-xorg_%.bbappend` causes a fetcher failure as shown in the error below -- I also cannot find the relevant release in the xorg-xserver release tags: https://github.com/JeffyCN/xorg-xserver/tags?after=1.20.7_2023_04_07.

```
ERROR: ExpansionError during parsing /home/hal/PROJECT/poky/meta/recipes-graphics/xorg-xserver/xserver-xorg_21.1.8.bb
Traceback (most recent call last):
  File "/home/hal/PROJECT/poky/bitbake/lib/bb/fetch2/git.py", line 250, in Git.urldata_init(ud=<bb.fetch2.FetchData object at 0x7fdabd84d6a0>, d=<bb.data_smart.DataSmart object at 0x7fdabcc04400>):
     
    >        ud.setup_revisions(d)
     
  File "/home/hal/PROJECT/poky/bitbake/lib/bb/fetch2/__init__.py", line 1349, in FetchData.setup_revisions(d=<bb.data_smart.DataSmart object at 0x7fdabcc04400>):
             for name in self.names:
    >            self.revisions[name] = srcrev_internal_helper(self, d, name)
     
  File "/home/hal/PROJECT/poky/bitbake/lib/bb/fetch2/__init__.py", line 1214, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7fdabd84d6a0>, d=<bb.data_smart.DataSmart object at 0x7fdabcc04400>, name='default'):
         if srcrev == "AUTOINC":
    >        srcrev = ud.method.latest_revision(ud, d, name)
     
  File "/home/hal/PROJECT/poky/bitbake/lib/bb/fetch2/__init__.py", line 1626, in Git.latest_revision(ud=<bb.fetch2.FetchData object at 0x7fdabd84d6a0>, d=<bb.data_smart.DataSmart object at 0x7fdabcc04400>, name='default'):
             except KeyError:
    >            revs[key] = rev = self._latest_revision(ud, d, name)
                 return rev
  File "/home/hal/PROJECT/poky/bitbake/lib/bb/fetch2/git.py", line 762, in Git._latest_revision(ud=<bb.fetch2.FetchData object at 0x7fdabd84d6a0>, d=<bb.data_smart.DataSmart object at 0x7fdabcc04400>, name='default'):
             raise bb.fetch2.FetchError("Unable to resolve '%s' in upstream git repository in git ls-remote output for %s" % \
    >            (ud.unresolvedrev[name], ud.host+ud.path))
     
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Unable to resolve '21.1.8_2022_11_03' in upstream git repository in git ls-remote output for github.com/JeffyCN/xorg-xserver
The variable dependency chain for the failure is: SRCPV -> AUTOREV[vardepvalue]

ERROR: Parsing halted due to errors, see error messages above
```

Looking forward to hearing from you,
HAL.

**Comment by JeffyCN** [comment]
the 21.1.8 was supported in 2023, i've uploaded the fix just now :)
